


name: staging
description: Staging environment for pre-production testing and validation


protection_rules:
  required_reviewers: 1
  wait_timer: 0
  prevent_self_review: true


variables:
  AWS_REGION: us-east-1
  STAGE: staging
  LOG_LEVEL: INFO
  FAILURE_RATE: "0.3"
  POWERTOOLS_LOG_LEVEL: INFO
  POWERTOOLS_LOGGER_SAMPLE_RATE: "0.5"


required_secrets:
  - AWS_ACCESS_KEY_ID_STAGING
  - AWS_SECRET_ACCESS_KEY_STAGING
  - AWS_REGION_STAGING


optional_secrets:
  - SNYK_TOKEN
  - CODECOV_TOKEN


deployment:
  auto_deploy_on: 
    - push_to_develop
    - manual_trigger
  
  pre_deployment_checks:
    - lint
    - unit_tests
    - integration_tests
    - security_scan
    
  post_deployment_actions:
    - e2e_tests
    - performance_tests
    - health_checks
